base/urls.py
# Copyright 2021 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

from django.urls import path

from base import views

app_name = "base"

urlpatterns = [
    path("", views.base_view, name="base"),
    path("profile/user-settings", views.profile_settings, name="settings"),
    path("profile/add-world", views.add_world, name="add_world"),
    path("profile/premium", views.premium_view, name="premium"),
    path("profile/payment-done", views.payment_done, name="payment_done"),
    path("overview/<str:token>", views.overview_view, name="overview"),
    path("planer/", views.OutlineList.as_view(), name="planer"),
    path("planer/show-all", views.OutlineListShowAll.as_view(), name="planer_all"),
    path("planer/create/", views.new_outline_create, name="planer_create"),
    path("planer/<int:_id>/status", views.inactive_outline, name="planer_status"),
    path("planer/<int:_id>", views.outline_detail, name="planer_detail"),
    path("planer/<int:_id>/delete", views.outline_delete, name="planer_delete"),
    path("documentation", views.base_documentation, name="documentation"),
    path(
        "planer/<int:_id>/delete/ally-tags",
        views.outline_delete_ally_tags,
        name="planer_delete_ally_tags",
    ),
    path(
        "planer/<int:_id>/delete/enemy-tags",
        views.outline_delete_enemy_tags,
        name="planer_delete_enemy_tags",
    ),
    path(
        "planer/<int:_id>/disable_editable",
        views.outline_disable_editable,
        name="planer_disable_editable",
    ),
    path(
        "planer/<int:_id>/results",
        views.outline_detail_results,
        name="planer_detail_results",
    ),
    path(
        "planer/<int:_id>/planer-form",
        views.initial_form,
        name="planer_initial_form",
    ),
    path(
        "planer/<int:_id>/planer-menu",
        views.initial_planer,
        name="planer_initial",
    ),
    path(
        "planer/<int:id1>/complete",
        views.complete_outline,
        name="planer_complete",
    ),
    path(
        "planer/<int:id1>/update_troops",
        views.update_outline_troops,
        name="planer_update_troops",
    ),
    path(
        "planer/planer-menu/delete-time/<int:pk>",
        views.initial_delete_time,
        name="planer_delete_time",
    ),
    path(
        "planer/planer-menu/set-all-time/<int:pk>",
        views.initial_set_all_time,
        name="planer_set_all_time",
    ),
    path(
        "planer/<int:id1>/planer-target/<int:id2>",
        views.initial_target,
        name="planer_initial_detail",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first",
        views.initial_add_first,
        name="planer_add_first",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first_off",
        views.initial_add_first_off,
        name="planer_add_first_off",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first_ruin",
        views.initial_add_first_ruin,
        name="planer_add_first_ruin",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first_fake",
        views.initial_add_first_fake,
        name="planer_add_first_fake",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first_fake_noble",
        views.initial_add_first_fake_noble,
        name="planer_add_first_fake_noble",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last_fake",
        views.initial_add_last_fake,
        name="planer_add_last_fake",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last_fake_noble",
        views.initial_add_last_fake_noble,
        name="planer_add_last_fake_noble",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last_ruin",
        views.initial_add_last_ruin,
        name="planer_add_last_ruin",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last",
        views.initial_add_last,
        name="planer_add_last",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last_off",
        views.initial_add_last_off,
        name="planer_add_last_off",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/hide",
        views.initial_hide_weight,
        name="planer_hide_weight",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id4>/up",
        views.initial_move_up,
        name="planer_move_up",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id4>/<int:n>",
        views.initial_divide,
        name="planer_divide",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id4>/down",
        views.initial_move_down,
        name="planer_move_down",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id4>/delete",
        views.initial_weight_delete,
        name="planer_initial_delete",
    ),
    path(
        "planer/<int:_id>/get-deff",
        views.outline_detail_get_deff,
        name="planer_detail_get_deff",
    ),
    path(
        "planer/<int:_id>/create/select-tribe",
        views.new_outline_create_select,
        name="planer_create_select",
    ),
]

tribal_wars_planer/urls.py
# Copyright 2021 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""tribal_wars_planer URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.one_step.views import RegistrationView

from tribal_wars_planer import forms

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("api/", include("rest_api.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path(
        "register/",
        RegistrationView.as_view(form_class=forms.RecaptchaRegistrationForm),
        name="django_registration_register",
    ),
    path("", include("django_registration.backends.one_step.urls")),
    path("", include("django.contrib.auth.urls")),
)

base/forms.py
# Copyright 2021 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

""" App forms """

from django import forms
from django.db.models.query import QuerySet
from django.forms import BaseFormSet
from django.utils.translation import gettext_lazy

from utils import basic, database_update

from . import models


class OutlineForm(forms.Form):
    """New Outline Form"""

    name = forms.CharField(
        max_length=20,
        label=gettext_lazy("Outline Name"),
        widget=forms.Textarea,
    )
    date = forms.DateField(label=gettext_lazy("Date"), input_formats=["%Y-%m-%d"])
    world = forms.ChoiceField(choices=[], label=gettext_lazy("World"))


class OffTroopsForm(forms.ModelForm):
    """Pasted data from army script"""

    class Meta:
        model = models.Outline
        fields = ["off_troops"]
        labels = {"off_troops": gettext_lazy("Army collection")}
        widgets = {
            "off_troops": forms.Textarea(
                attrs={"spellcheck": "false", "autocomplete": "off"}
            )
        }

    def __init__(self, *args, **kwargs):
        self.outline = kwargs.pop("outline")
        super(OffTroopsForm, self).__init__(*args, **kwargs)
        self.fields["off_troops"].strip = False

    def clean_off_troops(self):
        """User's input from script"""
        text = self.cleaned_data["off_troops"]
        if text == "":
            self.add_error(field=None, error=gettext_lazy("Text cannot be empty!"))
            return None

        player_dictionary = basic.coord_to_player(self.outline)
        evidence = basic.world_evidence(self.outline.world)

        already_used_villages = set()

        for i, text_line in enumerate(text.split("\r\n")):
            army = basic.Army(text_army=text_line, evidence=evidence)
            try:
                army.clean_init(player_dictionary)
            except basic.ArmyError:
                self.add_error("off_troops", i)  # type: ignore
                continue

            if army.coord in already_used_villages:
                self.add_error("off_troops", i)  # type: ignore
                continue
            else:
                already_used_villages.add(army.coord)

        return text


class DeffTroopsForm(forms.ModelForm):
    """Pasted data from defence script"""

    class Meta:
        model = models.Outline
        fields = {"deff_troops"}
        labels = {"deff_troops": gettext_lazy("Deff collection")}
        widgets = {
            "deff_troops": forms.Textarea(
                attrs={"spellcheck": "false", "autocomplete": "off"}
            )
        }

    def __init__(self, *args, **kwargs):
        self.outline = kwargs.pop("outline")
        super(DeffTroopsForm, self).__init__(*args, **kwargs)
        self.fields["deff_troops"].strip = False

    def clean_deff_troops(self):
        """User's input from script"""
        text = self.cleaned_data["deff_troops"]
        if text == "":
            self.add_error(field=None, error=gettext_lazy("Text cannot be empty!"))
            return None

        player_dictionary = basic.coord_to_player(self.outline)
        evidence = basic.world_evidence(self.outline.world)

        already_used_villages = dict()

        for i, text_line in enumerate(text.split("\r\n")):
            army = basic.Defence(text_army=text_line, evidence=evidence)
            try:
                army.clean_init(player_dictionary)
            except basic.DefenceError:
                self.add_error("deff_troops", i)  # type: ignore
                continue
            if army.coord in already_used_villages:
                already_used_villages[army.coord] += 1
                if already_used_villages[army.coord] > 2:
                    self.add_error("deff_troops", i)  # type: ignore
            else:
                already_used_villages[army.coord] = 1

        return text


class MyTribeTagForm(forms.Form):
    """Add ally tribes to outline"""

    tribe1 = forms.ChoiceField(
        choices=[], label=gettext_lazy("Ally tribe"), required=False
    )

    def clean_tribe1(self):
        """User's tags input"""
        plemie = self.cleaned_data["tribe1"]
        if plemie == "banned":
            self.add_error("tribe1", gettext_lazy("Select tribe from list"))
            return None
        return plemie


class EnemyTribeTagForm(forms.Form):
    """Add enemy tribes to outline"""

    tribe2 = forms.ChoiceField(
        choices=[], label=gettext_lazy("Enemy tribe"), required=False
    )

    def clean_tribe2(self):
        """User's tag input"""
        plemie = self.cleaned_data["tribe2"]
        if plemie == "banned":
            self.add_error("tribe2", gettext_lazy("Select tribe from list"))
            return None
        return plemie


class GetDeffForm(forms.Form):
    """GetDeff function"""

    radius = forms.IntegerField(
        min_value=0,
        max_value=1000,
        label=gettext_lazy("Radius"),
        widget=forms.NumberInput,
        help_text=gettext_lazy(
            "Greater than or equal to 0 and less than or equal to 1000."
        ),
        initial=15,
    )

    excluded = forms.CharField(
        max_length=3000,
        widget=forms.Textarea,
        label=gettext_lazy("Excluded enemy secluded villages"),
        required=False,
        help_text=gettext_lazy("Exact coords separated by a space or an entry."),
    )

    def __init__(self, *args, **kwargs):
        self.world = kwargs.pop("world")
        super(GetDeffForm, self).__init__(*args, **kwargs)

    def clean_excluded(self):
        """Excluded Villages"""
        villages = self.cleaned_data["excluded"]
        try:
            basic.many_villages(self.cleaned_data["excluded"])
        except basic.VillageError as error:
            self.add_error("excluded", str(error))
            return None
        return villages


class InitialOutlineForm(forms.Form):
    """New Initial Outline"""

    target = forms.CharField(
        max_length=50000,
        widget=forms.Textarea,
        label=gettext_lazy("Targets"),
        required=False,
        strip=False,
    )

    def __init__(self, *args, **kwargs):
        self.outline: models.Outline = kwargs.pop("outline")
        self.target_mode: basic.TargetMode = kwargs.pop("target_mode")
        super(InitialOutlineForm, self).__init__(*args, **kwargs)

    def clean_target(self):
        """User's input Targets"""

        data = self.cleaned_data["target"]
        data_lines = basic.TargetsData(data=data, world=self.outline.world)
        if data == "":
            data_lines.new_validated_data = ""
        else:
            data_lines.validate()

        if len(data_lines.errors_ids) == 0:
            if self.target_mode.is_real:
                self.outline.initial_outline_targets = (
                    data_lines.new_validated_data.strip()
                )
            elif self.target_mode.is_fake:
                self.outline.initial_outline_fakes = (
                    data_lines.new_validated_data.strip()
                )
            else:
                self.outline.initial_outline_ruins = (
                    data_lines.new_validated_data.strip()
                )
            self.outline.save()

        for error_id in data_lines.errors_ids:
            self.add_error("target", error_id)
        return data


class AvailableTroopsForm(forms.ModelForm):
    class Meta:
        model = models.Outline
        fields = [
            "initial_outline_min_off",
            "initial_outline_front_dist",
            "initial_outline_maximum_front_dist",
            "initial_outline_target_dist",
            "initial_outline_excluded_coords",
        ]
        labels = {
            "initial_outline_min_off": gettext_lazy("Min. off units number"),
            "initial_outline_front_dist": gettext_lazy(
                "Minimum distance from front line"
            ),
            "initial_outline_maximum_front_dist": gettext_lazy(
                "Maximum distance from front line"
            ),
            "initial_outline_target_dist": gettext_lazy("Max Distance for nobles"),
        }
        help_texts = {
            "initial_outline_min_off": gettext_lazy(
                "Greater than or equal to 1 and less than or equal to 28000. Only offs above this value will be considered full offs and will be written out."
            ),
            "initial_outline_front_dist": gettext_lazy(
                "Greater than or equal to 0 and less than or equal to 500. Villages closer to the enemy than this value will be considered front-line and not written out by default."
            ),
            "initial_outline_maximum_front_dist": gettext_lazy(
                "Greater than or equal to 0 and less than or equal to 1000. Villages farther from the enemy than this value will be considered too far from the front and completely skipped."
            ),
            "initial_outline_target_dist": gettext_lazy(
                "Greater than or equal to 0 and less than or equal to 1000."
            ),
        }

    initial_outline_excluded_coords = forms.CharField(
        label=gettext_lazy("Excluded enemy villages coords (secluded villages)"),
        required=False,
        max_length=100000,
        help_text=gettext_lazy("Exact coords separated by a space or an entry"),
        widget=forms.Textarea,
    )

base/templates/base/new_outline/new_outline.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{{instance.name|capfirst}} - {{instance.world.human}}{% endblock %}
{% block sidebar %}
    <a class=" list-group-item list-group-item-action bg-secondary" style="color: rgb(243, 243, 243);" href="{% url 'base:planer_detail' instance.id %}" role="button">{{instance.name}}</a>
    <a href="{% url 'base:planer_detail_results' instance.id %}" class="list-group-item list-group-item-action bg-light">{% trans 'Results' %}</a>
    <a href="{% url 'base:planer_detail_get_deff' instance.id %}" class="list-group-item list-group-item-action bg-light">{% trans 'Deff collection' %}</a>
    <a id="planer-link" onclick="onPlanerLinkClick(`{% trans 'Hold on a second...' %}`);" href="{% url 'base:planer_initial_form' instance.id %}" class="list-group-item list-group-item-action bg-light">{% trans 'Planer' %}</a>
{% endblock %}
{% block phonesidebar %}
    <a class=" list-group-item list-group-item-action bg-secondary" href="{% url 'base:planer_detail' instance.id %}" role="button">{{instance.name}}</a>
    <a href="{% url 'base:planer_detail_results' instance.id %}" class="list-group-item list-group-item-action bg-light">{% trans 'Results' %}</a>
    <a href="{% url 'base:planer_detail_get_deff' instance.id %}" class="list-group-item list-group-item-action bg-light">{% trans 'Deff collection' %}</a>
    <a href="{% url 'base:planer_initial_form' instance.id %}" class="list-group-item list-group-item-action bg-light">{% trans 'Planer' %}</a> 
{% endblock %}
{% block content %}
<div class="row mt-3 mb-4">
    <div class="col-12 col-lg-7">
        <div>
            <div class="p-3 mb-2 bg-light text-dark"><i class="bi bi-info-square"></i> {% trans 'Last world update: ' %}{{instance.world.update}}</div>
        </div>
        
        <script src="{% static 'codemirror-min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'codemirror-min.css' %}">
        
        <div class="row">
        
            <div class="col-12">
                <form method='POST'>
                    <input type="hidden" name="form-1" value="">
                    {% csrf_token %}
        
                    <div>
                        <div>
                            <h4 style="display: inline-block;" id="off-form-label">{{ form1.off_troops.label_tag }} </h4>
                            {% if message_off %}
                            <div style="display: inline-block;" id="message_off" class="alert alert-success my-0 py-0" role="alert">
                                <span style="font-size: small !important;">{% trans 'Army troops have been successfully added.' %}</span>
                            </div>
                            <script>
                                document.addEventListener("DOMContentLoaded", function(event) {
                                    const message = document.getElementById('message_off');
                                    setTimeout(() => {
                                        message.style.display = 'none';
                                    }, 2000)
                                });
                            </script>
                            {% endif %}
                        </div> 

                        {{ form1.off_troops }} 
                        {% if off_troops.errors %} 
                        <script>codemirrorValidation(`{{off_troops.get_json|safe}}`, `.cm-s-off-troops-codemirror`);</script>

                        <div class="error-text">
                            <p class="mb-0">{% trans 'Incorrect data in' %} {{off_troops.errors|length}} {% trans 'lines.' %}</p>
                            <p class="mt-0">{% trans '*After clicking submit you will be transferred to first error*' %}</p>
                        </div>
        
                        {% endif %} 
                        {% if off_troops.empty %} 
                        <div class="error-text mb-3">
                            {% trans 'The text cannot be empty' %}.
                        </div>
                        <script>
                            document.addEventListener("DOMContentLoaded", function(event) {
                                $('.cm-s-off-troops-codemirror').addClass('CodeMirror-Invalid');
                            });
                        </script> 
                        {% endif %}
                    </div>
                    <button onclick="this.disabled=true;this.form.submit();" class="btn btn-ocean my-3">{% trans 'Submit' %}</button>
                </form>
            </div>
            <script>
                var editor1 = CodeMirror.fromTextArea(document.getElementById("id_off_troops"), {
                    theme: 'off-troops-codemirror',
                    lineNumbers: true,
                });
                editor1.replaceSelection(`{{off_troops.troops}}`)
            </script>
        
            <div class="col-12">
                <form method='POST'>
                    <input type="hidden" name="form-2" value="">
                    {% csrf_token %}
        
                    <div>
                        <div>
                            <h4 style="display: inline-block;" id="deff-form-label">{{ form2.deff_troops.label_tag }}</h4>
                            {% if message_deff %}
                            <div style="display: inline-block;" id="message_deff" class="alert alert-success my-0 py-0" role="alert">
                                <span style="font-size: small !important;">{% trans 'Deff troops have been successfully added.' %}</span>
                            </div>
                            <script>
                                document.addEventListener("DOMContentLoaded", function(event) {
                                    document.getElementById('deff-form-label').scrollIntoView({behavior: "smooth"});
                                    const message = document.getElementById('message_deff');
                                    setTimeout(() => {
                                        message.style.display = 'none';
                                    }, 2000)
                                });
                            </script>
                            {% endif %}
                        </div>
                        {{ form2.deff_troops }} 

                        {% if deff_troops.errors %}
                        
                        <script>codemirrorValidation(`{{deff_troops.get_json|safe}}`, `.cm-s-deff-troops-codemirror`);</script>
                        <script>
                            document.addEventListener("DOMContentLoaded", function(event) {
                                document.getElementById('deff-form-label').scrollIntoView({behavior: "smooth"});
                            });
                        </script>
                    
                        <div class="error-text mb-3">
                            <p class="mb-0">{% trans 'Incorrect data in' %} {{deff_troops.errors|length}} {% trans 'lines.' %}</p>
                            <p class="mt-0">{% trans '*After clicking submit you will be transferred to first error*' %}</p>
                        </div>
        
                        {% endif %} 
                        {% if deff_troops.empty %} 
                        <div class="error-text mb-3">
                            {% trans 'The text cannot be empty' %}.
                        </div>
                        <script>
                            document.addEventListener("DOMContentLoaded", function(event) {
                                $('.cm-s-deff-troops-codemirror').addClass('CodeMirror-Invalid');
                            });
                        </script>
                        {% endif %}
                    </div>
                    <button onclick="this.disabled=true;this.form.submit();" class="btn btn-ocean my-3">{% trans 'Submit' %}</button>
                </form>
            </div>
            <script>
                var editor2 = CodeMirror.fromTextArea(document.getElementById("id_deff_troops"), {
                    theme: 'deff-troops-codemirror',
                    lineNumbers: true,
                });
                editor2.replaceSelection(`{{deff_troops.troops}}`)
            </script>
            {% if not deff_troops.errors and not message_deff %}
            <script>window.scrollTo(0,0)</script>
            {% endif %}
        </div>
    </div>
    <div class="col-12 col-lg-5" style="border-left: 1px solid #ddd;">
        <div class="h-100">
            <ul class="nav nav-pills mb-3 mt-1" id="pills-tab" role="tablist">
                <li class="nav-item navitem100">
                    <a class="nav-link active ocean-tab-left" id="pills-home-tab" data-toggle="pill" href="#pills-opis" role="tab" aria-controls="pills-home" aria-selected="true">{% trans 'Info' %}</a>
                </li>
                <li class="nav-item navitem100">
                    <a class="nav-link ocean-tab-right" id="pills-contact-tab" data-toggle="pill" href="#pills-przyklady" role="tab" aria-controls="pills-contact" aria-selected="false">{% trans 'Examples' %}</a>
                </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-opis" role="tabpanel" aria-labelledby="pills-home-tab">
                    {{info|safe}}
                </div>
                <div class="tab-pane fade" id="pills-przyklady" role="tabpanel" aria-labelledby="pills-contact-tab">
                    {{example|safe}}
                </div>
            </div>
        </div>
    </div>
</div>


{% if error != None %}

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content text-white bg-danger">
            <div class="modal-header">
                <h3 class="modal-title">{% trans 'An error occured' %}</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{error|safe}}
            </div>
        </div>
    </div>
</div>



<script>
    document.addEventListener("DOMContentLoaded", function(event) {
        $('.bd-example-modal-lg').modal('show');


    });
</script>

{% endif %} {% endblock %}

base/templates/base/new_outline/new_outline_create.html
{% extends 'base/base.html' %} 
{% load i18n %} 
{% block title %}{% trans 'Create new outline' %}{% endblock %}
{% block content %} 
{% load crispy_forms_tags %}

<div class="row mt-3 mb-4">
    <div class="col-12 col-lg-7">

        <div class="p-3 mb-2 bg-light text-dark"><i class="bi bi-info-square"></i> {% trans 'Your server is set to' %} <a href="{% url 'base:settings' %}" class="font-teal" style="text-decoration: underline;">{{profile.server}}.</a></div>


        <div class="p-3 mb-2 bg-light text-dark"><i class="bi bi-info-square"></i> {% trans 'First time? You can choose a special <span class="md-correct2">World Test</span> created for testing purposes, see ' %}<a target="_blank" class="font-teal" style="text-decoration: underline;" href="{% url 'base:documentation' %}#swiat-testowy-czyli-pierwsze-kroki-z-planerem">{% trans 'docs' %}</a>.</div>

        <form method='POST' autocomplete="off">
            {% csrf_token %} 
            {{ form1|crispy }}
            <button onclick="this.disabled=true;this.form.submit();" class="btn btn-ocean mb-5 mt-2">
                {% trans 'Create' %}
            </button>
        </form>
        
    </div>
 
    <div class="col-12 col-lg-5" style="border-left: 1px solid #ddd;">
        <div class="h-100">
            <ul class="nav nav-pills mb-3 mt-1" id="pills-tab" role="tablist">
                <li class="nav-item navitem100">
                    <a class="nav-link active ocean-tab-left" id="pills-home-tab" data-toggle="pill" href="#pills-opis" role="tab" aria-controls="pills-home" aria-selected="true">{% trans 'Info' %}</a>
                </li>
                <li class="nav-item navitem100">
                    <a class="nav-link ocean-tab-right" id="pills-contact-tab" data-toggle="pill" href="#pills-przyklady" role="tab" aria-controls="pills-contact" aria-selected="false">{% trans 'Examples' %}</a>
                </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-opis" role="tabpanel" aria-labelledby="pills-home-tab">
                    {{info|safe}}
                </div>
                <div class="tab-pane fade" id="pills-przyklady" role="tabpanel" aria-labelledby="pills-contact-tab">
                    {{example|safe}}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}