base/urls.py
# Copyright 2021 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

from django.urls import path

from base import views

app_name = "base"

urlpatterns = [
    path("", views.base_view, name="base"),
    path("profile/user-settings", views.profile_settings, name="settings"),
    path("profile/add-world", views.add_world, name="add_world"),
    path("profile/premium", views.premium_view, name="premium"),
    path("profile/payment-done", views.payment_done, name="payment_done"),
    path("overview/<str:token>", views.overview_view, name="overview"),
    path("planer/", views.OutlineList.as_view(), name="planer"),
    path("planer/show-all", views.OutlineListShowAll.as_view(), name="planer_all"),
    path("planer/create/", views.new_outline_create, name="planer_create"),
    path("planer/<int:_id>/status", views.inactive_outline, name="planer_status"),
    path("planer/<int:_id>", views.outline_detail, name="planer_detail"),
    path("planer/<int:_id>/delete", views.outline_delete, name="planer_delete"),
    path("documentation", views.base_documentation, name="documentation"),
    path(
        "planer/<int:_id>/delete/ally-tags",
        views.outline_delete_ally_tags,
        name="planer_delete_ally_tags",
    ),
    path(
        "planer/<int:_id>/delete/enemy-tags",
        views.outline_delete_enemy_tags,
        name="planer_delete_enemy_tags",
    ),
    path(
        "planer/<int:_id>/disable_editable",
        views.outline_disable_editable,
        name="planer_disable_editable",
    ),
    path(
        "planer/<int:_id>/results",
        views.outline_detail_results,
        name="planer_detail_results",
    ),
    path(
        "planer/<int:_id>/planer-form",
        views.initial_form,
        name="planer_initial_form",
    ),
    path(
        "planer/<int:_id>/planer-menu",
        views.initial_planer,
        name="planer_initial",
    ),
    path(
        "planer/<int:id1>/complete",
        views.complete_outline,
        name="planer_complete",
    ),
    path(
        "planer/<int:id1>/update_troops",
        views.update_outline_troops,
        name="planer_update_troops",
    ),
    path(
        "planer/planer-menu/delete-time/<int:pk>",
        views.initial_delete_time,
        name="planer_delete_time",
    ),
    path(
        "planer/planer-menu/set-all-time/<int:pk>",
        views.initial_set_all_time,
        name="planer_set_all_time",
    ),
    path(
        "planer/<int:id1>/planer-target/<int:id2>",
        views.initial_target,
        name="planer_initial_detail",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first",
        views.initial_add_first,
        name="planer_add_first",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first_off",
        views.initial_add_first_off,
        name="planer_add_first_off",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first_ruin",
        views.initial_add_first_ruin,
        name="planer_add_first_ruin",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first_fake",
        views.initial_add_first_fake,
        name="planer_add_first_fake",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_first_fake_noble",
        views.initial_add_first_fake_noble,
        name="planer_add_first_fake_noble",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last_fake",
        views.initial_add_last_fake,
        name="planer_add_last_fake",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last_fake_noble",
        views.initial_add_last_fake_noble,
        name="planer_add_last_fake_noble",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last_ruin",
        views.initial_add_last_ruin,
        name="planer_add_last_ruin",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last",
        views.initial_add_last,
        name="planer_add_last",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/add_last_off",
        views.initial_add_last_off,
        name="planer_add_last_off",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id3>/hide",
        views.initial_hide_weight,
        name="planer_hide_weight",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id4>/up",
        views.initial_move_up,
        name="planer_move_up",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id4>/<int:n>",
        views.initial_divide,
        name="planer_divide",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id4>/down",
        views.initial_move_down,
        name="planer_move_down",
    ),
    path(
        "planer/<int:id1>/<int:id2>/<int:id4>/delete",
        views.initial_weight_delete,
        name="planer_initial_delete",
    ),
    path(
        "planer/<int:_id>/get-deff",
        views.outline_detail_get_deff,
        name="planer_detail_get_deff",
    ),
    path(
        "planer/<int:_id>/create/select-tribe",
        views.new_outline_create_select,
        name="planer_create_select",
    ),
]

tribal_wars_planer/urls.py
# Copyright 2021 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""tribal_wars_planer URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.one_step.views import RegistrationView

from tribal_wars_planer import forms

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("api/", include("rest_api.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path(
        "register/",
        RegistrationView.as_view(form_class=forms.RecaptchaRegistrationForm),
        name="django_registration_register",
    ),
    path("", include("django_registration.backends.one_step.urls")),
    path("", include("django.contrib.auth.urls")),
)

base/forms.py
# Copyright 2021 Rafał Safin (rafsaf). All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

""" App forms """

from django import forms
from django.db.models.query import QuerySet
from django.forms import BaseFormSet
from django.utils.translation import gettext_lazy

from utils import basic, database_update

from . import models


class OutlineForm(forms.Form):
    """New Outline Form"""

    name = forms.CharField(
        max_length=20,
        label=gettext_lazy("Outline Name"),
        widget=forms.Textarea,
    )
    date = forms.DateField(label=gettext_lazy("Date"), input_formats=["%Y-%m-%d"])
    world = forms.ChoiceField(choices=[], label=gettext_lazy("World"))


class OffTroopsForm(forms.ModelForm):
    """Pasted data from army script"""

    class Meta:
        model = models.Outline
        fields = ["off_troops"]
        labels = {"off_troops": gettext_lazy("Army collection")}
        widgets = {
            "off_troops": forms.Textarea(
                attrs={"spellcheck": "false", "autocomplete": "off"}
            )
        }

    def __init__(self, *args, **kwargs):
        self.outline = kwargs.pop("outline")
        super(OffTroopsForm, self).__init__(*args, **kwargs)
        self.fields["off_troops"].strip = False

    def clean_off_troops(self):
        """User's input from script"""
        text = self.cleaned_data["off_troops"]
        if text == "":
            self.add_error(field=None, error=gettext_lazy("Text cannot be empty!"))
            return None

        player_dictionary = basic.coord_to_player(self.outline)
        evidence = basic.world_evidence(self.outline.world)

        already_used_villages = set()

        for i, text_line in enumerate(text.split("\r\n")):
            army = basic.Army(text_army=text_line, evidence=evidence)
            try:
                army.clean_init(player_dictionary)
            except basic.ArmyError:
                self.add_error("off_troops", i)  # type: ignore
                continue

            if army.coord in already_used_villages:
                self.add_error("off_troops", i)  # type: ignore
                continue
            else:
                already_used_villages.add(army.coord)

        return text


class DeffTroopsForm(forms.ModelForm):
    """Pasted data from defence script"""

    class Meta:
        model = models.Outline
        fields = {"deff_troops"}
        labels = {"deff_troops": gettext_lazy("Deff collection")}
        widgets = {
            "deff_troops": forms.Textarea(
                attrs={"spellcheck": "false", "autocomplete": "off"}
            )
        }

    def __init__(self, *args, **kwargs):
        self.outline = kwargs.pop("outline")
        super(DeffTroopsForm, self).__init__(*args, **kwargs)
        self.fields["deff_troops"].strip = False

    def clean_deff_troops(self):
        """User's input from script"""
        text = self.cleaned_data["deff_troops"]
        if text == "":
            self.add_error(field=None, error=gettext_lazy("Text cannot be empty!"))
            return None

        player_dictionary = basic.coord_to_player(self.outline)
        evidence = basic.world_evidence(self.outline.world)

        already_used_villages = dict()

        for i, text_line in enumerate(text.split("\r\n")):
            army = basic.Defence(text_army=text_line, evidence=evidence)
            try:
                army.clean_init(player_dictionary)
            except basic.DefenceError:
                self.add_error("deff_troops", i)  # type: ignore
                continue
            if army.coord in already_used_villages:
                already_used_villages[army.coord] += 1
                if already_used_villages[army.coord] > 2:
                    self.add_error("deff_troops", i)  # type: ignore
            else:
                already_used_villages[army.coord] = 1

        return text


class MyTribeTagForm(forms.Form):
    """Add ally tribes to outline"""

    tribe1 = forms.ChoiceField(
        choices=[], label=gettext_lazy("Ally tribe"), required=False
    )

    def clean_tribe1(self):
        """User's tags input"""
        plemie = self.cleaned_data["tribe1"]
        if plemie == "banned":
            self.add_error("tribe1", gettext_lazy("Select tribe from list"))
            return None
        return plemie


class EnemyTribeTagForm(forms.Form):
    """Add enemy tribes to outline"""

    tribe2 = forms.ChoiceField(
        choices=[], label=gettext_lazy("Enemy tribe"), required=False
    )

    def clean_tribe2(self):
        """User's tag input"""
        plemie = self.cleaned_data["tribe2"]
        if plemie == "banned":
            self.add_error("tribe2", gettext_lazy("Select tribe from list"))
            return None
        return plemie


class GetDeffForm(forms.Form):
    """GetDeff function"""

    radius = forms.IntegerField(
        min_value=0,
        max_value=1000,
        label=gettext_lazy("Radius"),
        widget=forms.NumberInput,
        help_text=gettext_lazy(
            "Greater than or equal to 0 and less than or equal to 1000."
        ),
        initial=15,
    )

    excluded = forms.CharField(
        max_length=3000,
        widget=forms.Textarea,
        label=gettext_lazy("Excluded enemy secluded villages"),
        required=False,
        help_text=gettext_lazy("Exact coords separated by a space or an entry."),
    )

    def __init__(self, *args, **kwargs):
        self.world = kwargs.pop("world")
        super(GetDeffForm, self).__init__(*args, **kwargs)

    def clean_excluded(self):
        """Excluded Villages"""
        villages = self.cleaned_data["excluded"]
        try:
            basic.many_villages(self.cleaned_data["excluded"])
        except basic.VillageError as error:
            self.add_error("excluded", str(error))
            return None
        return villages


class InitialOutlineForm(forms.Form):
    """New Initial Outline"""

    target = forms.CharField(
        max_length=50000,
        widget=forms.Textarea,
        label=gettext_lazy("Targets"),
        required=False,
        strip=False,
    )

    def __init__(self, *args, **kwargs):
        self.outline: models.Outline = kwargs.pop("outline")
        self.target_mode: basic.TargetMode = kwargs.pop("target_mode")
        super(InitialOutlineForm, self).__init__(*args, **kwargs)

    def clean_target(self):
        """User's input Targets"""

        data = self.cleaned_data["target"]
        data_lines = basic.TargetsData(data=data, world=self.outline.world)
        if data == "":
            data_lines.new_validated_data = ""
        else:
            data_lines.validate()

        if len(data_lines.errors_ids) == 0:
            if self.target_mode.is_real:
                self.outline.initial_outline_targets = (
                    data_lines.new_validated_data.strip()
                )
            elif self.target_mode.is_fake:
                self.outline.initial_outline_fakes = (
                    data_lines.new_validated_data.strip()
                )
            else:
                self.outline.initial_outline_ruins = (
                    data_lines.new_validated_data.strip()
                )
            self.outline.save()

        for error_id in data_lines.errors_ids:
            self.add_error("target", error_id)
        return data


class AvailableTroopsForm(forms.ModelForm):
    class Meta:
        model = models.Outline
        fields = [
            "initial_outline_min_off",
            "initial_outline_front_dist",
            "initial_outline_maximum_front_dist",
            "initial_outline_target_dist",
            "initial_outline_excluded_coords",
        ]
        labels = {
            "initial_outline_min_off": gettext_lazy("Min. off units number"),
            "initial_outline_front_dist": gettext_lazy(
                "Minimum distance from front line"
            ),
            "initial_outline_maximum_front_dist": gettext_lazy(
                "Maximum distance from front line"
            ),
            "initial_outline_target_dist": gettext_lazy("Max Distance for nobles"),
        }
        help_texts = {
            "initial_outline_min_off": gettext_lazy(
                "Greater than or equal to 1 and less than or equal to 28000. Only offs above this value will be considered full offs and will be written out."
            ),
            "initial_outline_front_dist": gettext_lazy(
                "Greater than or equal to 0 and less than or equal to 500. Villages closer to the enemy than this value will be considered front-line and not written out by default."
            ),
            "initial_outline_maximum_front_dist": gettext_lazy(
                "Greater than or equal to 0 and less than or equal to 1000. Villages farther from the enemy than this value will be considered too far from the front and completely skipped."
            ),
            "initial_outline_target_dist": gettext_lazy(
                "Greater than or equal to 0 and less than or equal to 1000."
            ),
        }

    initial_outline_excluded_coords = forms.CharField(
        label=gettext_lazy("Excluded enemy villages coords (secluded villages)"),
        required=False,
        max_length=100000,
        help_text=gettext_lazy("Exact coords separated by a space or an entry"),
        widget=forms.Textarea,
    )

base/templates/base/base_planer.html
{% extends 'base/base.html' %} 
{% load i18n %} 
{% block title %}{% trans 'My outlines' %}{% endblock %}
{% block content %}
<div class="table-responsive">
<table class="table table-striped mt-3">
    <thead style="background-color: teal;">
        <tr style="color: white;">
            <th class='text-nowrap' scope="col" style="border:1px solid teal">{% trans 'Outline Name' %}</th>
            <th scope="col" style="border:1px solid teal">{% trans 'Date' %}</th>
            <th scope="col" style="border:1px solid teal">{% trans 'Created' %}</th>
            <th scope="col" style="border:1px solid teal">{% trans 'World' %}</th>
            <th scope="col" style="border:1px solid teal">{% trans 'Ally' %}</th>
            <th scope="col" style="border:1px solid teal">{% trans 'Enemy' %}</th>
            <th scope="col" style="border:1px solid teal">{% trans 'Hide' %}</th>
            <th scope="col" style="border:1px solid teal">{% trans 'Delete' %}</th>
        </tr>
    </thead>
    <tbody>

        {% for instance in object_list %}
        <tr>
            <td>
                <a class="btn btn-secondary my-2" href="{% url 'base:planer_detail' instance.id %}" role="button">{{instance.name}}</a>
            </td>
            <td><p class="my-2 mt-3">{{instance.date}}</p></td>
            <td><p class="my-2 mt-3">{{instance.created}}<br>{{instance.expires_in|safe}}</p></td>
            <td><p class="my-2 mt-3">{{instance.world_human}}</p></td>
            <td><p class="my-2 mt-3">{{instance.ally_tribe_tag}}</p></td>
            <td><p class="my-2 mt-3">{{instance.enemy_tribe_tag}}</p></td>
            <td>
                {% if instance.status == 'active' %}

                <form action="{% url 'base:planer_status' instance.id %}" method="POST">
                    {% csrf_token %}
                    <button onclick="this.disabled=true;this.form.submit();" class="btn btn-secondary my-2">{% trans 'Hide' %}</button>
                </form>

                {% else %}

                <form action="{% url 'base:planer_status' instance.id %}" method="POST">
                    {% csrf_token %}
                    <button onclick="this.disabled=true;this.form.submit();" class="btn btn-secondary my-2">{% trans 'Show' %}</button>
                </form>

                {% endif %}

            </td>
            <td>
                <div>
                    <button type="button" class="btn btn-secondary my-2" data-toggle="modal" data-target="#ValidationModal-{{instance.id}}">{% trans 'Delete' %}</button>
                </div>

                <div class="modal fade" id="ValidationModal-{{instance.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">{% trans 'Warning' %}</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <h4 class="md-correct2">{{instance.name}}</h4>
                                <p>{% trans "You will lose all progress on this outline. The orders (weights), targets, entered script results and any data will be deleted forever too. The generated links will remain valid as is, but you will no longer be able to access them through the Results tab. You may consider hiding this outline instead of deleting it." %}</p>

                                <h5 class="md-error mt-2">{% trans "This operation cannot be undone!" %}</h5>
                                
                            </div>
                            <div class="modal-footer">

                                <button id="dismiss-{{instance.id}}-btn" type="button" class="btn btn-secondary" data-dismiss="modal">
                                    <b>{% trans 'Close' %}</b>
                                </button>

                                <form id="form-{{instance.id}}-form" action="{% url 'base:planer_delete' instance.id %}" method="POST">
                                    {% csrf_token %}
                                    <button onclick="removeOutline(this,`dismiss-{{instance.id}}-btn`,`form-{{instance.id}}-form`,`{% trans 'Processing...' %}`)" class="btn btn-danger">{% trans 'Delete forever' %}</button>
                
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            {% endfor %}
    </tbody>
</table>
</div>

{% if show_all == True %}
<p><a class="btn btn-outline-ocean my-3" href="{% url 'base:planer' %}" role="button">{% trans "Don't show hidden" %}</a></p>
{% else %}
<p><a class="btn btn-outline-ocean my-3" href="{% url 'base:planer_all' %}" role="button">{% trans 'Show hidden' %}</a></p>
{% endif %} 

{% endblock %}

base/templates/base/documentation.html
{% extends 'base/base.html' %}
{% load i18n %} {% load static %} 
{% block title %}{% trans 'Documentation' %}{% endblock %}
{% block meta-content %}<meta name="description" content="{% trans 'Documentation of Tribal Wars Planer, professional tool for creating outlines for off-game coordinators.' %}"/>{% endblock %}
{% block content %}{% autoescape off %} 

<div id='docs' class="container" style="font-size: larger;max-width:900px;">
    <article style="margin-left:-15px!important;margin-right:-15px;">
        {{doc}}
    </article>
</div>
{% endautoescape %}
<script>
    var bg_color_img_box = 'rgba(0,0,0,0.9)';
    var allow_hide_scroll_img_box = 'yes';
    var use_fade_inout_img_box = 'yes';
    var speed_img_box = 0.08;
    var z_index_dv_img_box = 999;
    var vopa_img_box, idpopup_img_box;
    imagePopupActivate();
</script>

{% endblock %}